---
name: Checks

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: codeberg-small

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: https://github.com/DeterminateSystems/nix-installer-action@v16
      - name: Check Formatting
        run: nix fmt -- --ci
      - name: Flake Check
        run: nix flake check -L
